#!/bin/bash
# Shared helpers for zipcode installation entrypoints.

zipcode_install_dir() {
    printf '%s\n' "${ZIPCODE_INSTALL_DIR:-${HOME}/.zipcode}"
}

zipcode_install_bin_dir() {
    printf '%s\n' "$(zipcode_install_dir)/bin"
}

zipcode_model_dir() {
    printf '%s\n' "$(zipcode_install_dir)/models"
}

zipcode_session_dir() {
    printf '%s\n' "$(zipcode_install_dir)/sessions"
}

zipcode_setup_env_path() {
    printf '%s\n' "$(zipcode_install_dir)/setup.env"
}

zipcode_next_steps_path() {
    printf '%s\n' "$(zipcode_install_dir)/NEXT_STEPS.txt"
}

zipcode_config_path() {
    printf '%s\n' "$(zipcode_install_dir)/config.json"
}

zipcode_user_bin_dir() {
    printf '%s\n' "${HOME}/.local/bin"
}

find_first_existing() {
    local candidate
    for candidate in "$@"; do
        if [ -e "${candidate}" ]; then
            printf '%s\n' "${candidate}"
            return 0
        fi
    done
    return 1
}

copy_executable() {
    local source_path="$1"
    local target_path="$2"
    cp "${source_path}" "${target_path}"
    chmod 755 "${target_path}"
}

ensure_install_dirs() {
    mkdir -p \
        "$(zipcode_install_dir)" \
        "$(zipcode_install_bin_dir)" \
        "$(zipcode_model_dir)" \
        "$(zipcode_session_dir)"
}

write_default_config() {
    local config_file="${1:-$(zipcode_config_path)}"
    local model_dir="${2:-$(zipcode_model_dir)}"

    if [ -f "${config_file}" ]; then
        echo "Preserving existing config: ${config_file}"
        return
    fi

    mkdir -p "$(dirname -- "${config_file}")"
    cat > "${config_file}" <<EOF
{
  "model_dir": "${model_dir}",
  "permission_mode": "workspace-write"
}
EOF
    echo "Wrote default config: ${config_file}"
}

write_setup_env() {
    local setup_env="$1"
    local install_bin_dir="$2"
    local user_bin_dir="$3"
    local llama_server_path="${4:-}"

    mkdir -p "$(dirname -- "${setup_env}")"
    cat > "${setup_env}" <<EOF
# Generated by zipcode install
export PATH="${install_bin_dir}:${user_bin_dir}:\$PATH"
EOF

    if [ -n "${llama_server_path}" ]; then
        cat >> "${setup_env}" <<EOF
export ZIPCODE_LLAMA_SERVER_BIN="${llama_server_path}"
EOF
    fi
}

ensure_user_launcher() {
    local launcher_source="$1"
    local user_bin_dir="${2:-$(zipcode_user_bin_dir)}"
    mkdir -p "${user_bin_dir}"
    ln -sf "${launcher_source}" "${user_bin_dir}/zipcode"
    printf '%s\n' "${user_bin_dir}/zipcode"
}

path_contains_dir() {
    local dir="$1"
    case ":${PATH:-}:" in
        *":${dir}:"*) return 0 ;;
        *) return 1 ;;
    esac
}
