#!/bin/bash
# scripts/install.sh — Install zipcode from an extracted bundle
set -euo pipefail

INSTALL_DIR="${HOME}/.zipcode"
INSTALL_BIN_DIR="${INSTALL_DIR}/bin"
MODEL_DIR="${INSTALL_DIR}/models"
SESSION_DIR="${INSTALL_DIR}/sessions"
SETUP_ENV="${INSTALL_DIR}/setup.env"
NEXT_STEPS_FILE="${INSTALL_DIR}/NEXT_STEPS.txt"
CONFIG_FILE="${INSTALL_DIR}/config.json"
SYSTEM_BIN_DIR="/usr/local/bin"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

find_first_existing() {
    local candidate
    for candidate in "$@"; do
        if [ -e "${candidate}" ]; then
            printf '%s\n' "${candidate}"
            return 0
        fi
    done
    return 1
}

copy_executable() {
    local source_path="$1"
    local target_path="$2"
    cp "${source_path}" "${target_path}"
    chmod 755 "${target_path}"
}

write_default_config() {
    if [ -f "${CONFIG_FILE}" ]; then
        echo "Preserving existing config: ${CONFIG_FILE}"
        return
    fi

    cat > "${CONFIG_FILE}" <<EOF
{
  "model_dir": "${MODEL_DIR}",
  "permission_mode": "workspace-write"
}
EOF
    echo "Wrote default config: ${CONFIG_FILE}"
}

write_setup_env() {
    local llama_server_path="$1"

    cat > "${SETUP_ENV}" <<EOF
# Generated by zipcode install.sh
export PATH="${INSTALL_BIN_DIR}:\$PATH"
EOF

    if [ -n "${llama_server_path}" ]; then
        cat >> "${SETUP_ENV}" <<EOF
export ZIPCODE_LLAMA_SERVER_BIN="${llama_server_path}"
EOF
    fi
}

write_next_steps() {
    local llama_server_path="$1"
    local helper_path="$2"

    {
        echo "Next steps:"
        echo "  1. Copy your model into ${MODEL_DIR}:"
        echo "     cp /path/to/model.gguf \"${MODEL_DIR}/\""
        echo "  2. Copy the matching tokenizer into ${MODEL_DIR}:"
        echo "     cp /path/to/tokenizer.json \"${MODEL_DIR}/\""
        echo "  3. Load the generated environment so bare zipcode resolves:"
        echo "     source \"${SETUP_ENV}\""
        echo "  4. Start zipcode:"
        echo "     zipcode"
        echo "  5. If first run says setup or repair is needed:"
        echo "     zipcode doctor"
        echo "     zipcode setup --skip-smoke"

        if [ -n "${llama_server_path}" ]; then
            echo ""
            echo "Bundled llama-server installed at ${llama_server_path}."
            echo "The generated ${SETUP_ENV} file already exports ZIPCODE_LLAMA_SERVER_BIN."
            echo "First run and repair flows will pick it up automatically."
        elif [ -n "${helper_path}" ]; then
            echo ""
            echo "No bundled llama-server was found."
            echo "If first run later says Gemma 4 needs the fallback server, install it with:"
            echo "  \"${helper_path}\" /path/to/llama-server \"${INSTALL_DIR}\""
        else
            echo ""
            echo "No bundled llama-server was found."
            echo "If first run later says Gemma 4 needs the fallback server, set:"
            echo "  export ZIPCODE_LLAMA_SERVER_BIN=/path/to/llama-server"
        fi
    } > "${NEXT_STEPS_FILE}"
}

echo "Installing zipcode into ${INSTALL_DIR}..."

mkdir -p "${INSTALL_DIR}" "${INSTALL_BIN_DIR}" "${MODEL_DIR}" "${SESSION_DIR}"

ZIPCODE_SOURCE="$(find_first_existing \
    "${SCRIPT_DIR}/zipcode" \
    "${PWD}/zipcode")" || {
    echo "Error: zipcode binary not found next to install.sh or in the current directory" >&2
    exit 1
}

copy_executable "${ZIPCODE_SOURCE}" "${INSTALL_DIR}/zipcode"
ln -sf "../zipcode" "${INSTALL_BIN_DIR}/zipcode"

HELPER_SOURCE="$(find_first_existing \
    "${SCRIPT_DIR}/install_llama_server.sh" \
    "${SCRIPT_DIR}/scripts/install_llama_server.sh" \
    "${PWD}/install_llama_server.sh" || true)"
HELPER_INSTALLED=""
if [ -n "${HELPER_SOURCE}" ]; then
    HELPER_INSTALLED="${INSTALL_DIR}/install_llama_server.sh"
    copy_executable "${HELPER_SOURCE}" "${HELPER_INSTALLED}"
fi

LLAMA_SERVER_SOURCE="$(find_first_existing \
    "${SCRIPT_DIR}/llama-server" \
    "${SCRIPT_DIR}/bin/llama-server" \
    "${PWD}/llama-server" \
    "${PWD}/bin/llama-server" || true)"
LLAMA_SERVER_INSTALLED=""
if [ -n "${LLAMA_SERVER_SOURCE}" ]; then
    echo "Detected bundled llama-server: ${LLAMA_SERVER_SOURCE}"
    if [ -n "${HELPER_INSTALLED}" ]; then
        "${HELPER_INSTALLED}" "${LLAMA_SERVER_SOURCE}" "${INSTALL_DIR}" >/dev/null
    else
        LLAMA_SERVER_INSTALLED="${INSTALL_BIN_DIR}/llama-server"
        copy_executable "${LLAMA_SERVER_SOURCE}" "${LLAMA_SERVER_INSTALLED}"
    fi
    LLAMA_SERVER_INSTALLED="${INSTALL_BIN_DIR}/llama-server"
fi

write_default_config
write_setup_env "${LLAMA_SERVER_INSTALLED}"
write_next_steps "${LLAMA_SERVER_INSTALLED}" "${HELPER_INSTALLED}"

if [ -d "${SYSTEM_BIN_DIR}" ] && [ -w "${SYSTEM_BIN_DIR}" ]; then
    ln -sf "${INSTALL_BIN_DIR}/zipcode" "${SYSTEM_BIN_DIR}/zipcode"
    echo "Installed zipcode into ${SYSTEM_BIN_DIR}/zipcode"
else
    echo "Could not update ${SYSTEM_BIN_DIR}; use: source \"${SETUP_ENV}\""
fi

echo
cat "${NEXT_STEPS_FILE}"
